derived_columns: [data_source]

data_sources:
  source1: ${PROCESSED}/DESeq-Packager/expr_tsv/RNA_EWS-FLI1_{ews_fli1}_{treatment_drug}_rep{rep}.tsv


metadata:
  output_dir: ${PROCESSED}/DESeq-Packager/output_results
  sample_annotation: ${PROCESSED}/DESeq-Packager/table_experiments_RNA.csv

